// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Mt_Gshu-RFaF-fHYhLrDwZ_jjNDzG7s',
    appId: '1:954782046444:web:7f48597f22b8cac0f72dc9',
    messagingSenderId: '954782046444',
    projectId: 'smart-tech-5d678',
    authDomain: 'smart-tech-5d678.firebaseapp.com',
    storageBucket: 'smart-tech-5d678.appspot.com',
    measurementId: 'G-HQ34FCQ7EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEk3fk5wTY0tZ6g9Xf0LPr_UxQ0JfWSEY',
    appId: '1:954782046444:android:4e6fa5c91200800ff72dc9',
    messagingSenderId: '954782046444',
    projectId: 'smart-tech-5d678',
    storageBucket: 'smart-tech-5d678.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxipXB6uqwHyNvLDfyDx-GNXc2rbCypV8',
    appId: '1:954782046444:ios:953e8520726ab48bf72dc9',
    messagingSenderId: '954782046444',
    projectId: 'smart-tech-5d678',
    storageBucket: 'smart-tech-5d678.appspot.com',
    iosClientId: '954782046444-9ccqaja7hdann838phe33viee9trihqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.hardAndSoftMobile',
  );
}
